export const COLORS = {
  BG: '#0a0a0f',
  DEBUG_TEXT: '#3a3a4a'
};

export const GAME = {
  TARGET_FPS: 60,
  MAX_DT: 1 / 30,
  SCROLL_SPEED: 200,
  SPAWN_INTERVAL: 2.0,
  MIN_OBSTACLE_GAP: 120,
  MAX_OBSTACLES: 4,
  OBSTACLE_WIDTH: 48,
  OBSTACLE_HEIGHT: 56,
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 32,
  GROUND_HEIGHT: 40,
  PLAYER_X_PERCENT: 0.12,
  DANGER_ZONE_START: 0.3
};
